INSERT INTO book(id, author, title) VALUES (1,'Arnold Sommerfeld','Lectures on Theoretical Physics');
INSERT INTO book(id, author, title) VALUES (2,'Richard Feynman', 'The Feynman lectures on Physics');
INSERT INTO book(id, author,title) VALUES (3,'Jearle Walker','The Flying Circus of Physics');
INSERT INTO book(id, author, title) VALUES (4,'Paul Davies', 'The New Physics');
INSERT INTO book(id, author, title) VALUES (5,'Richard Feynman', 'The Character of Physical Law');
INSERT INTO book(id, author, title) VALUES (6,'David Mermin', 'Communicating science in prosaic language');
INSERT INTO book(id, author, title) VALUES (7,'Herbert Goldstein', 'Classical Mechanics');
INSERT INTO book(id, author, title) VALUES (8,'Keith Symon', 'Mechanics');
INSERT INTO book(id, author, title) VALUES (9,'Kiran Gupta', 'Classical Mechanics of Particles and Rigid Bodies');
INSERT INTO book(id, author, title) VALUES (10,'Jackson', 'Classical Electrodynamics');
INSERT INTO book(id, author, title) VALUES (11,'William Smythe', 'Static and Dynamic Electricity');
